# Reserved IP, tagged like the current setup so it survives `tofu destroy`
# (destroy removes the server, keeps this IP for the next session).
resource "scaleway_instance_ip" "main" {
  zone = var.zone
  tags = [var.instance_name]

  lifecycle {
    prevent_destroy = true # keep the IP stable across sessions
  }
}

resource "scaleway_instance_server" "main" {
  name  = var.instance_name
  type  = var.instance_type
  image = var.image_id
  zone  = var.zone
  ip_id = scaleway_instance_ip.main.id
  tags  = [var.instance_name]

  root_volume {
    size_in_gb = var.root_volume_size_gb
  }
}

# Wait for sshd, mirroring the until-loop in infra/start.sh.
resource "null_resource" "wait_for_ssh" {
  triggers = { server_id = scaleway_instance_server.main.id }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      host        = scaleway_instance_ip.main.address
      user        = "root"
      private_key = file(replace(var.ssh_public_key_path, ".pub", ""))
    }
    inline = ["echo provisioning-host-ready"]
  }
}

# Generate the Ansible inventory so `make configure` needs no manual IP wiring.
resource "local_file" "inventory" {
  filename = "${path.module}/../ansible/inventory/${var.flavor}.ini"
  content  = <<-EOT
    # Generated by OpenTofu — do not edit by hand.
    [${var.flavor}]
    ${scaleway_instance_ip.main.address} ansible_user=root

    [${var.flavor}:vars]
    flavor=${var.flavor}
  EOT
}
